from .file.covers import CoverProcess
from .ingest.doab import DOABProcess
from .ingest.gutenberg import GutenbergProcess
from .ingest.hathi_trust import HathiTrustProcess
from .ingest.nypl import NYPLProcess
from .frbr.catalog import CatalogProcess
from .frbr.classify import ClassifyProcess
from .cluster import ClusterProcess
from .local_development.local_development_setup import LocalDevelopmentSetupProcess
from .local_development.seed_local_data import SeedLocalDataProcess
from .file.s3_files import S3Process
from .api import APIProcess
from .ingest.muse import MUSEProcess
from .ingest.met import METProcess
from .util.db_maintenance import DatabaseMaintenanceProcess
from .util.db_migration import MigrationProcess
from .ingest.chicago_isac import ChicagoISACProcess
from .ingest.loc import LOCProcess
from .ingest.publisher_backlist import PublisherBacklistProcess
from .ingest.clacso import CLACSOProcess
from .record_ingestor import RecordIngestor
from .link_fulfiller import LinkFulfiller
from .record_frbrizer import RecordFRBRizer
from .record_clusterer import RecordClusterer
