import datetime


TEST_NYPL_BIB = {
    "id": "11239943",
    "updated_date": datetime.datetime(2025, 1, 30, 21, 9, 26),
    "created_date": datetime.datetime(2008, 12, 14, 20, 8),
    "deleted_date": None,
    "deleted": False,
    "locations": [
        {"code": "mai", "name": "SASB - Microforms Rm 315"},
        {"code": "map", "name": "SASB - Map Division - Rm 117"},
    ],
    "suppressed": False,
    "available": None,
    "lang": {"code": "eng", "name": "English"},
    "title": "The iconography of Manhattan Island, 1498-1909 : compiled from original sources and illustrated by photo-intaglio reproductions of important maps, plans, views, and documents in public and private collections",
    "author": "Stokes, I. N. Phelps (Isaac Newton Phelps), 1867-1944.",
    "material_type": {"code": "a  ", "value": "BOOK/TEXT"},
    "bib_level": {"code": "m", "value": "MONOGRAPH"},
    "publish_year": 1915,
    "catalog_date": datetime.date(2000, 10, 21),
    "country": {"code": "nyu", "name": "New York (State)"},
    "norm_title": "iconography of manhattan island 1498 1909 compiled from original sources and illustrated by photo intaglio reproductions of important maps plans views and documents in public and private collections",
    "norm_author": "stokes i n phelps isaac newton phelps 1867 1944",
    "fixed_fields": {
        "24": {"label": "Language", "value": "eng", "display": "English"},
        "25": {"label": "Skip", "value": "4", "display": None},
        "26": {"label": "Location", "value": "multi", "display": None},
        "27": {"label": "", "value": "2", "display": None},
        "28": {"label": "Cat. Date", "value": "2000-10-21", "display": None},
        "29": {"label": "Bib Level", "value": "m", "display": "MONOGRAPH"},
        "30": {"label": "Material Type", "value": "a  ", "display": "BOOK/TEXT"},
        "31": {"label": "Bib Code 3", "value": "-", "display": None},
        "80": {"label": "Record Type", "value": "b", "display": None},
        "81": {"label": "Record Number", "value": "11239943", "display": None},
        "83": {
            "label": "Created Date",
            "value": "2008-12-14T20:08:00Z",
            "display": None,
        },
        "84": {
            "label": "Updated Date",
            "value": "2025-01-30T21:09:26Z",
            "display": None,
        },
        "85": {"label": "No. of Revisions", "value": "18", "display": None},
        "86": {"label": "Agency", "value": "1", "display": None},
        "89": {"label": "Country", "value": "nyu", "display": "New York (State)"},
        "98": {"label": "", "value": "2022-08-01T07:40:00Z", "display": None},
        "107": {"label": "MARC Type", "value": " ", "display": None},
    },
    "var_fields": [
        {
            "ind1": "1",
            "ind2": " ",
            "content": None,
            "marcTag": "100",
            "fieldTag": "a",
            "subfields": [
                {"tag": "a", "content": "Stokes, I. N. Phelps"},
                {"tag": "q", "content": "(Isaac Newton Phelps),"},
                {"tag": "d", "content": "1867-1944."},
            ],
        },
        {
            "ind1": "1",
            "ind2": " ",
            "content": None,
            "marcTag": "700",
            "fieldTag": "b",
            "subfields": [
                {"tag": "a", "content": "Paltsits, Victor Hugo,"},
                {"tag": "d", "content": "1867-1952."},
            ],
        },
        {
            "ind1": "1",
            "ind2": " ",
            "content": None,
            "marcTag": "700",
            "fieldTag": "b",
            "subfields": [
                {"tag": "a", "content": "Wieder, F. C."},
                {"tag": "q", "content": "(Frederik Caspar),"},
                {"tag": "d", "content": "1874-1943."},
            ],
        },
        {
            "ind1": " ",
            "ind2": "0",
            "content": None,
            "marcTag": "650",
            "fieldTag": "d",
            "subfields": [
                {"tag": "a", "content": "Cartography"},
                {"tag": "z", "content": "United States"},
                {"tag": "x", "content": "History."},
            ],
        },
        {
            "ind1": " ",
            "ind2": "0",
            "content": None,
            "marcTag": "650",
            "fieldTag": "d",
            "subfields": [
                {"tag": "a", "content": "American newspapers"},
                {"tag": "z", "content": "New York (State)"},
                {"tag": "z", "content": "New York"},
                {"tag": "v", "content": "Bibliography."},
            ],
        },
        {
            "ind1": " ",
            "ind2": "0",
            "content": None,
            "marcTag": "651",
            "fieldTag": "d",
            "subfields": [
                {"tag": "a", "content": "New York (N.Y.)"},
                {"tag": "x", "content": "History."},
            ],
        },
        {
            "ind1": " ",
            "ind2": "0",
            "content": None,
            "marcTag": "651",
            "fieldTag": "d",
            "subfields": [
                {"tag": "a", "content": "New York (N.Y.)"},
                {"tag": "v", "content": "Pictorial works."},
            ],
        },
        {
            "ind1": " ",
            "ind2": "0",
            "content": None,
            "marcTag": "651",
            "fieldTag": "d",
            "subfields": [
                {"tag": "a", "content": "New York (N.Y.)"},
                {"tag": "v", "content": "Maps."},
            ],
        },
        {
            "ind1": " ",
            "ind2": "0",
            "content": None,
            "marcTag": "651",
            "fieldTag": "d",
            "subfields": [
                {"tag": "a", "content": "New York (N.Y.)"},
                {"tag": "v", "content": "Bibliography."},
            ],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "010",
            "fieldTag": "l",
            "subfields": [{"tag": "a", "content": "16000765"}],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "035",
            "fieldTag": "l",
            "subfields": [{"tag": "a", "content": "(WaOLN)nyp1247592"}],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "035",
            "fieldTag": "l",
            "subfields": [{"tag": "a", "content": "(OCoLC)20774798"}],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "500",
            "fieldTag": "n",
            "subfields": [{"tag": "a", "content": "Engraved title page."}],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "500",
            "fieldTag": "n",
            "subfields": [
                {
                    "tag": "a",
                    "content": '"Of this book three hundred and sixty copies have been printed on English hand-made paper and forty-two on Japanese vellum."',
                }
            ],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "504",
            "fieldTag": "n",
            "subfields": [
                {
                    "tag": "a",
                    "content": "Bibliography, by Victor H. Paltsits: v. 6, p. [179]-281.",
                }
            ],
        },
        {
            "ind1": "0",
            "ind2": " ",
            "content": None,
            "marcTag": "505",
            "fieldTag": "n",
            "subfields": [
                {
                    "tag": "a",
                    "content": "v. 1. The period of discovery (1524-1609); the Dutch period (1609-1664). The English period (1664-1763). The Revolutionary period (1763-1783). Period of adjustment and reconstruction; New York as the state and federal capital (1783-1811) -- v. 2. Cartography: an essay on the development of knowledge regarding the geography of the east coast of North America; Manhattan Island and its environs on early maps and charts / by F.C. Wieder and I.N. Phelps Stokes. The Manatus maps. The Castello plan. The Dutch grants. Early New York newspapers (1725-1811). Plan of Manhattan Island in 1908 -- v. 3. The War of 1812 (1812-1815). Period of invention, prosperity, and progress (1815-1841). Period of industrial and educational development (1842-1860). The Civil War (1861-1865); period of political and social development (1865-1876). The modern city and island (1876-1909) -- v. 4. The period of discovery (565-1626); the Dutch period (1626-1664). The English period (1664-1763). The Revolutionary period, part I (1763-1776) -- v. 5. The Revolutionary period, part II (1776-1783). Period of adjustment and reconstruction New York as the state and federal capital (1783-1811). The War of 1812 (1812-1815) ; period of invention, prosperity, and progress (1815-1841). Period of industrial and educational development (1842-1860). The Civil War (1861-1865) ; Period of political and social development (1865-1876). The modern city and island (1876-1909) --",
                }
            ],
        },
        {
            "ind1": "0",
            "ind2": " ",
            "content": None,
            "marcTag": "505",
            "fieldTag": "n",
            "subfields": [
                {
                    "tag": "a",
                    "content": "v. 6. Chronology: addenda. Original grants and farms. Bibliography. Index.",
                }
            ],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": "NYPG89-B73631",
            "marcTag": "001",
            "fieldTag": "o",
            "subfields": None,
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "260",
            "fieldTag": "p",
            "subfields": [
                {"tag": "a", "content": "New York :"},
                {"tag": "b", "content": "Robert H. Dodd,"},
                {"tag": "c", "content": "1915-1928."},
            ],
        },
        {
            "ind1": "8",
            "ind2": " ",
            "content": None,
            "marcTag": "852",
            "fieldTag": "q",
            "subfields": [
                {"tag": "h", "content": "*ZH-1"},
                {"tag": "z", "content": "Library has v. 1-3"},
            ],
        },
        {
            "ind1": "8",
            "ind2": " ",
            "content": None,
            "marcTag": "852",
            "fieldTag": "q",
            "subfields": [
                {"tag": "h", "content": "*ZH-2"},
                {"tag": "z", "content": "Library has v. 4-6"},
            ],
        },
        {
            "ind1": "0",
            "ind2": "1",
            "content": None,
            "marcTag": "852",
            "fieldTag": "q",
            "subfields": [
                {"tag": "k", "content": "*R-Map Div. Desk"},
                {"tag": "h", "content": "F128"},
                {"tag": "i", "content": ".37.S87  "},
            ],
        },
        {
            "ind1": "8",
            "ind2": " ",
            "content": None,
            "marcTag": "852",
            "fieldTag": "q",
            "subfields": [
                {
                    "tag": "h",
                    "content": "*KAF (New York City) (Stokes, I. N. P. Iconography of Manhattan Island)",
                }
            ],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "300",
            "fieldTag": "r",
            "subfields": [
                {"tag": "a", "content": "6 v. :"},
                {
                    "tag": "b",
                    "content": "ill. (some col., some folded), facsims., maps, ;",
                },
                {"tag": "c", "content": "29 cm."},
            ],
        },
        {
            "ind1": "1",
            "ind2": "4",
            "content": None,
            "marcTag": "245",
            "fieldTag": "t",
            "subfields": [
                {
                    "tag": "a",
                    "content": "The iconography of Manhattan Island, 1498-1909 :",
                },
                {
                    "tag": "b",
                    "content": "compiled from original sources and illustrated by photo-intaglio reproductions of important maps, plans, views, and documents in public and private collections /",
                },
                {"tag": "c", "content": "by I.N. Phelps Stokes."},
            ],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "959",
            "fieldTag": "v",
            "subfields": [
                {"tag": "a", "content": ".b22640617"},
                {"tag": "b", "content": "04-11-07"},
                {"tag": "c", "content": "08-29-91"},
            ],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": "20000629180221.0",
            "marcTag": "005",
            "fieldTag": "y",
            "subfields": None,
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": "891026m19151928nyuabfh  b    001 0 eng dcam a ",
            "marcTag": "008",
            "fieldTag": "y",
            "subfields": None,
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "040",
            "fieldTag": "y",
            "subfields": [
                {"tag": "a", "content": "MWA"},
                {"tag": "c", "content": "MWA"},
                {"tag": "d", "content": "NN"},
                {"tag": "d", "content": "WaOLN"},
            ],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "043",
            "fieldTag": "y",
            "subfields": [{"tag": "a", "content": "n-us-ny"}],
        },
        {
            "ind1": "0",
            "ind2": "0",
            "content": None,
            "marcTag": "050",
            "fieldTag": "y",
            "subfields": [
                {"tag": "a", "content": "F128"},
                {"tag": "b", "content": ".37.S87"},
            ],
        },
        {
            "ind1": "4",
            "ind2": "1",
            "content": None,
            "marcTag": "856",
            "fieldTag": "y",
            "subfields": [
                {
                    "tag": "u",
                    "content": "https://archive.org/details/iconographyofman01stok",
                },
                {
                    "tag": "z",
                    "content": "Full text available via Internet Archive (vol. 1)",
                },
            ],
        },
        {
            "ind1": "4",
            "ind2": "1",
            "content": None,
            "marcTag": "856",
            "fieldTag": "y",
            "subfields": [
                {
                    "tag": "u",
                    "content": "https://archive.org/details/iconographyofma_02stok",
                },
                {
                    "tag": "z",
                    "content": "Full text available via Internet Archive (vol. 2)",
                },
            ],
        },
        {
            "ind1": "4",
            "ind2": "1",
            "content": None,
            "marcTag": "856",
            "fieldTag": "y",
            "subfields": [
                {
                    "tag": "u",
                    "content": "https://archive.org/details/iconographyofman_b03stok",
                },
                {
                    "tag": "z",
                    "content": "Full text available via Internet Archive (vol. 3)",
                },
            ],
        },
        {
            "ind1": "4",
            "ind2": "1",
            "content": None,
            "marcTag": "856",
            "fieldTag": "y",
            "subfields": [
                {
                    "tag": "u",
                    "content": "https://archive.org/details/iconographyofman_a04stok",
                },
                {
                    "tag": "z",
                    "content": "Full text available via Internet Archive (vol. 4)",
                },
            ],
        },
        {
            "ind1": "4",
            "ind2": "1",
            "content": None,
            "marcTag": "856",
            "fieldTag": "y",
            "subfields": [
                {
                    "tag": "u",
                    "content": "https://archive.org/details/iconographyofman05stok",
                },
                {
                    "tag": "z",
                    "content": "Full text available via Internet Archive (vol. 5)",
                },
            ],
        },
        {
            "ind1": "4",
            "ind2": "1",
            "content": None,
            "marcTag": "856",
            "fieldTag": "y",
            "subfields": [
                {
                    "tag": "u",
                    "content": "https://archive.org/details/iconographyofman06stok",
                },
                {
                    "tag": "z",
                    "content": "Full text available via Internet Archive (vol. 6)",
                },
            ],
        },
        {
            "ind1": "0",
            "ind2": "0",
            "content": None,
            "marcTag": "908",
            "fieldTag": "y",
            "subfields": [
                {"tag": "a", "content": "F128"},
                {"tag": "b", "content": ".37.S87"},
            ],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "997",
            "fieldTag": "y",
            "subfields": [
                {"tag": "a", "content": "hm"},
                {"tag": "a", "content": "hsr"},
                {"tag": "b", "content": "10-21-00"},
                {"tag": "c", "content": "m"},
                {"tag": "d", "content": "a"},
                {"tag": "e", "content": "-"},
                {"tag": "f", "content": "eng"},
                {"tag": "g", "content": "nyu"},
                {"tag": "h", "content": "4"},
            ],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "991",
            "fieldTag": "y",
            "subfields": [{"tag": "y", "content": "20774798"}],
        },
        {
            "ind1": " ",
            "ind2": " ",
            "content": None,
            "marcTag": "910",
            "fieldTag": "y",
            "subfields": [{"tag": "a", "content": "RL"}],
        },
        {
            "ind1": None,
            "ind2": None,
            "content": "00000cam  2200373 a 4500",
            "marcTag": None,
            "fieldTag": "_",
            "subfields": None,
        },
    ],
    "nypl_source": "sierra-nypl",
    "nypl_type": "bib",
    "standard_numbers": [],
    "control_number": "NYPG89-B73631",
}