from .db import DBManager
from .kMeans import KMeansManager
from .oclcCatalog import OCLCCatalogManager
from .oclcClassify import ClassifyManager
from .rabbitmq import RabbitMQManager
from .redis import RedisManager
from .sfrRecord import SFRRecordManager
from .elasticsearch import ElasticsearchManager
from .sfrElasticRecord import SFRElasticRecordManager
from .s3 import S3Manager