from .coverManager import CoverManager
from .db import DBManager
from .doabParser import DOABLinkManager
from .gutenberg import GutenbergManager
from .kMeans import KMeansManager
from .oclcCatalog import OCLCCatalogManager
from .oclcClassify import ClassifyManager
from .nyplApi import NyplApiManager
from .pdfManifest import PDFManifest
from .rabbitmq import RabbitMQManager
from .redis import RedisManager
from .sfrRecord import SFRRecordManager
from .elasticsearch import ElasticsearchManager
from .sfrElasticRecord import SFRElasticRecordManager
from .s3 import S3Manager
from .smartsheet import SmartSheetManager