from .extractAllEditions import main as editionExtraction
from .updateOldInTechOpenLinks import main as updateInTechOpenLinks
from .updateESEditionFormats import main as updateESEditionFormat
from .updateLinksCatalog import main as updateLinks
from .updateRecordsCatalogLink import main as updateRecordCatalogs
from .govDocES import main as govDocUpdate
from .deleteElasticRecords import main as deleteESCRecords
from .esReIndex import main as esIndex
from .deleteDuplicateAgents import main as deleteDuplicates
from .chicago_isac_scraper import main as isacScraper
from .interstitialPagesSFR1410 import main as interstitialPages
from .ingestS3Metadata import main as ingestS3