from .gutenberg import GutenbergProcess
from .hathiTrust import HathiTrustProcess
from .nypl import NYPLProcess
from .oclcCatalog import CatalogProcess
from .oclcClassify import ClassifyProcess
from .sfrCluster import ClusterProcess
from .developmentSetup import DevelopmentSetupProcess
from .s3Files import S3Process
from .api import APIProcess
from .muse import MUSEProcess