from .covers import CoverProcess
from .doab import DOABProcess
from .gutenberg import GutenbergProcess
from .hathiTrust import HathiTrustProcess
from .nypl import NYPLProcess
from .oclcCatalog import CatalogProcess
from .oclcClassify import ClassifyProcess
from .cluster import ClusterProcess
from .local_development_setup import LocalDevelopmentSetupProcess
from .seed_local_data import SeedLocalDataProcess
from .s3Files import S3Process
from .api import APIProcess
from .muse import MUSEProcess
from .ingestReport import IngestReportProcess
from .met import METProcess
from .migration import MigrationProcess
from .dbMaintenance import DatabaseMaintenanceProcess
from .chicagoISAC import ChicagoISACProcess
from .UofSC import UofSCProcess
from .loc import LOCProcess
from .UofM import UofMProcess
from .fulfill_url_manifest import FulfillURLManifestProcess
