name: 'ETL Pipeline Tests (Self-Hosted)'

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'api/**'
      - 'managers/**'
      - 'mappings/**'
      - 'model/**'
      - 'processes/**'
      - 'services/**'
      - 'tests/**'
      - 'utils/**'
      - 'dev-requirements.txt'
      - 'requirements.txt'
      - 'main.py'
      - 'Makefile'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  PRIMARY_AWS_ACCOUNTID: "491147561046"
  SECONDARY_AWS_ACCOUNTID: "946183545209"
  IMAGE_TAG: nypl-nginx-test
  ENVIRONMENT: qa
  NYPL_BIB_USER: ${{ secrets.NYPL_BIB_USER }}
  NYPL_BIB_PASSWORD: ${{ secrets.NYPL_BIB_PASSWORD }}
  OCLC_WSKEY: ${{ secrets.OCLC_WSKEY }}
  OCLC_SECRET: ${{ secrets.OCLC_SECRET }}
  ELASTICSEARCH_HOST: ${{ secrets.ELASTICSEARCH_HOST }}
  ELASTICSEARCH_INDEX: ${{ secrets.ELASTICSEARCH_INDEX }}
  ELASTICSEARCH_PORT: ${{ secrets.ELASTICSEARCH_PORT }}
  ELASTICSEARCH_SCHEME: ${{ secrets.ELASTICSEARCH_SCHEME }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}

jobs:
  run-tests:
    runs-on: self-hosted
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure primary AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.PRIMARY_AWS_ACCOUNTID }}:role/GithubActionsRunnerRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GHAPrimarySession-${{ github.run_id }}
          audience: sts.amazonaws.com

      - name: Configure cross-account AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.SECONDARY_AWS_ACCOUNTID }}:role/GHACrossAccountRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GHASecondarySession-${{ github.run_id }}
          role-chaining: true
          role-duration-seconds: 1800
          audience: sts.amazonaws.com

      - name: Get GitHub API Key from SSM
        id: get-github-key
        run: |
          echo "Retrieving GitHub API key from SSM..."
          GITHUB_API_KEY=$(aws ssm get-parameter \
            --name "/drb/qa/github-key" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)
          
          # Mask the key in logs and set as output
          echo "::add-mask::$GITHUB_API_KEY"
          echo "GITHUB_API_KEY=${GITHUB_API_KEY}" >> $GITHUB_ENV
          echo "Key retrieved successfully"

      - name: Install Python 3.9 and build tools
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install -y \
            python3.9 \
            python3.9-dev \
            python3.9-venv \
            gcc \
            g++ \
            build-essential \
            cmake \
            libblas-dev \
            liblapack-dev \
            jq
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
          sudo update-alternatives --set python3 /usr/bin/python3.9

      - name: Add local bin to PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set up Python environment
        run: |
          python3 -m pip install --upgrade pip wheel
          pip install setuptools==58.2.0
          pip install pytest-rerunfailures  # Required for retry functionality
          pip install --prefer-binary -r requirements.txt -r dev-requirements.txt

      - name: Run QA integration tests
        env:
          GITHUB_API_KEY: ${{ env.GITHUB_API_KEY }}
        run: |
          python3 -m pytest tests/integration \
            --env=qa \
            --junitxml=test-results.xml \
            --reruns=3 \
            --reruns-delay=5

      - name: Run QA functional tests
        run: |
          python3 -m pytest tests/functional/processes/frbr \
            --env=qa \
            --junitxml=test-results.xml \
            --reruns=3 \
            --reruns-delay=5

      - name: Cleanup GitHub API Key
        run: |
          echo "Cleaning up GitHub API key..."
          unset GITHUB_API_KEY
          echo "GITHUB_API_KEY=" >> $GITHUB_ENV
